services:
  - type: web
    name: na-svyazi
    runtime: docker
    plan: free
    envVars:
      - key: TEACHER_PASSWORD
        generateValue: true
      - key: DB_PATH
        value: /var/data/results.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
